Region: us-east-1
Image:
  Os: alinux2
HeadNode:
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
  InstanceType: c5n.2xlarge
  Networking:
    SubnetId: <public-subnet-id> # us-east-1a
  Ssh:
    KeyName: delongmeng
  Dcv:
    Enabled: true
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - ComputeResources:
        - Instances:
            - InstanceType: p3dn.24xlarge
          MinCount: 0
          MaxCount: 2
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
          Name: p3dn
      Name: queue1
      Networking:
        SubnetIds:
          - <private-subnet-id> # us-east-1a
        PlacementGroup:
          Enabled: true
      CustomActions:
        OnNodeConfigured:
          Script: s3://my-ml-bucket/setup.sh
      Iam:
        S3Access:
          - BucketName: my-ml-bucket
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonSSMFullAccess
SharedStorage:
  - MountDir: /shared
    Name: default-ebs
    StorageType: Ebs
  - Name: fsxshared
    StorageType: FsxLustre
    MountDir: /lustre
    FsxLustreSettings:
      StorageCapacity: 1200
      ImportPath: s3://my-ml-bucket
      DeploymentType: SCRATCH_2
